### PR TITLE
handling certain categorical features with many distinct values

### PR DESCRIPTION
**Pull request by steremma**

### CODE REVIEW

**Comment by steremma** [comment]
Thanks for the review @joepvdbogaert let's merge in tomorrow's meeting together

**Comment by joepvdbogaert** [comment]
Oops, already merged. Nothing special here though, I guess?

**Comment by steremma** [comment]
I would prefer to squash before because now we also got two useless messages in the history: https://github.com/MLblog/jads_kaggle/commits/master

but its too much work to fix so i won't let my OCD get in the way of things :P

**Comment by joepvdbogaert** [comment]
Ah okay, sorry, I should have checked the commit history I guess. It's useful for me to have this PR merged before I create mine though.

**Comment by steremma** [comment]
Oh then it's fine you did well!

**Pull request merged**
